apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jigme-deploy
  name: jigme-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jigme-deploy
  template:
    metadata:
      labels:
        app: jigme-deploy
    spec:
      containers:
      - image: jigme95/jigme:19
        name: jigme
