apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pet-deploy
  name: jigme-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pet-deploy
  template:
    metadata:
      labels:
        app: pet-deploy
    spec:
      containers:
      - image: pemalodup/jigme:19
        name: jigme
